platform :ios, '6.0'
pod 'UIImage-Resize'
pod 'SIAlertView'
pod 'LAUtilitiesStaticLib'
pod 'BlocksKit'
pod 'ALActionBlocks'
pod 'WTGlyphFontSet'
pod 'WTGlyphFontSet/fontawesome'
pod 'HCYoutubeParser'
pod 'FoundationExtension'
pod 'RNGridMenu'
pod 'MBProgressHUD'
pod 'iOS7Colors'
pod 'CZPhotoPickerController'
pod 'BVReorderTableView', :head
pod 'AFNetworking','~>1.3.3'