platform :ios, '6.0'

pod 'SIAlertView'
pod 'XCDYouTubeVideoPlayerViewController'
pod 'LAUtilitiesStaticLib'
pod 'BlocksKit'
pod 'ALActionBlocks'
pod 'WTGlyphFontSet'
pod 'WTGlyphFontSet/social_foundicons'
pod 'WTGlyphFontSet/entypo'
pod 'WTGlyphFontSet/entypo-social'
pod 'WTGlyphFontSet/fontawesome'
pod 'WTGlyphFontSet/general_foundicons'
pod 'HCYoutubeParser'
pod 'IDMPhotoBrowser'
pod 'FoundationExtension'
pod 'RNGridMenu'
pod 'MBProgressHUD'
pod 'EGYWebViewController'
pod 'iOS7Colors'
