platform :ios, '6.1'
pod 'UIImage-Resize'
pod 'SIAlertView'
pod 'LAUtilitiesStaticLib'
pod 'BlocksKit'
pod 'ALActionBlocks'
pod 'WTGlyphFontSet'
pod 'WTGlyphFontSet/social_foundicons'
pod 'WTGlyphFontSet/entypo'
pod 'WTGlyphFontSet/entypo-social'
pod 'WTGlyphFontSet/fontawesome'
pod 'WTGlyphFontSet/general_foundicons'
pod 'HCYoutubeParser'
pod 'IDMPhotoBrowser','~> 1.2.5'
pod 'FoundationExtension'
pod 'RNGridMenu'
pod 'MBProgressHUD'
pod 'EGYWebViewController'
pod 'iOS7Colors'
pod 'CZPhotoPickerController'
pod 'BVReorderTableView', :head
pod 'SWTableViewCell'
pod 'AFNetworking'